services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: mydiary_mssql-server
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password.1234"
        ports:
            - "1433:1433"
    mydiary-api:
        build: ./
        container_name: mydiary-api
        environment:
            DatabaseServer: "mydiary_mssql-server"
            DatabasePort: "1433"
            DatabaseUser: "sa"
            DatabasePassword: "Password.1234"
            DatabaseName: "MyDiaryDB"
        depends_on:
            - mssql-server
        ports:
            - "8080:8080"

